/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnitsRouteImport } from './routes/units'
import { Route as StrategiesRouteImport } from './routes/strategies'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as ForumDemoRouteImport } from './routes/forum-demo'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as DoubleupRouteImport } from './routes/doubleup'
import { Route as DiscussionsRouteImport } from './routes/discussions'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForumIndexRouteImport } from './routes/forum/index'
import { Route as ForumDemoIndexRouteImport } from './routes/forum-demo.index'
import { Route as DiscussionsIndexRouteImport } from './routes/discussions/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as ForumCreatePostRouteImport } from './routes/forum.create-post'
import { Route as ForumPostIdRouteImport } from './routes/forum.$postId'
import { Route as ForumDemoPostIdRouteImport } from './routes/forum-demo.$postId'
import { Route as DiscussionsSlugRouteImport } from './routes/discussions.$slug'
import { Route as AccountConfirmationRouteImport } from './routes/account/confirmation'

const UnitsRoute = UnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesRoute = StrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumDemoRoute = ForumDemoRouteImport.update({
  id: '/forum-demo',
  path: '/forum-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const DoubleupRoute = DoubleupRouteImport.update({
  id: '/doubleup',
  path: '/doubleup',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscussionsRoute = DiscussionsRouteImport.update({
  id: '/discussions',
  path: '/discussions',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumIndexRoute = ForumIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ForumRoute,
} as any)
const ForumDemoIndexRoute = ForumDemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ForumDemoRoute,
} as any)
const DiscussionsIndexRoute = DiscussionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DiscussionsRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const ForumCreatePostRoute = ForumCreatePostRouteImport.update({
  id: '/create-post',
  path: '/create-post',
  getParentRoute: () => ForumRoute,
} as any)
const ForumPostIdRoute = ForumPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => ForumRoute,
} as any)
const ForumDemoPostIdRoute = ForumDemoPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => ForumDemoRoute,
} as any)
const DiscussionsSlugRoute = DiscussionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DiscussionsRoute,
} as any)
const AccountConfirmationRoute = AccountConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => AccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/discussions': typeof DiscussionsRouteWithChildren
  '/doubleup': typeof DoubleupRoute
  '/forum': typeof ForumRouteWithChildren
  '/forum-demo': typeof ForumDemoRouteWithChildren
  '/items': typeof ItemsRoute
  '/strategies': typeof StrategiesRoute
  '/units': typeof UnitsRoute
  '/account/confirmation': typeof AccountConfirmationRoute
  '/discussions/$slug': typeof DiscussionsSlugRoute
  '/forum-demo/$postId': typeof ForumDemoPostIdRoute
  '/forum/$postId': typeof ForumPostIdRoute
  '/forum/create-post': typeof ForumCreatePostRoute
  '/account/': typeof AccountIndexRoute
  '/discussions/': typeof DiscussionsIndexRoute
  '/forum-demo/': typeof ForumDemoIndexRoute
  '/forum/': typeof ForumIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/doubleup': typeof DoubleupRoute
  '/items': typeof ItemsRoute
  '/strategies': typeof StrategiesRoute
  '/units': typeof UnitsRoute
  '/account/confirmation': typeof AccountConfirmationRoute
  '/discussions/$slug': typeof DiscussionsSlugRoute
  '/forum-demo/$postId': typeof ForumDemoPostIdRoute
  '/forum/$postId': typeof ForumPostIdRoute
  '/forum/create-post': typeof ForumCreatePostRoute
  '/account': typeof AccountIndexRoute
  '/discussions': typeof DiscussionsIndexRoute
  '/forum-demo': typeof ForumDemoIndexRoute
  '/forum': typeof ForumIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/discussions': typeof DiscussionsRouteWithChildren
  '/doubleup': typeof DoubleupRoute
  '/forum': typeof ForumRouteWithChildren
  '/forum-demo': typeof ForumDemoRouteWithChildren
  '/items': typeof ItemsRoute
  '/strategies': typeof StrategiesRoute
  '/units': typeof UnitsRoute
  '/account/confirmation': typeof AccountConfirmationRoute
  '/discussions/$slug': typeof DiscussionsSlugRoute
  '/forum-demo/$postId': typeof ForumDemoPostIdRoute
  '/forum/$postId': typeof ForumPostIdRoute
  '/forum/create-post': typeof ForumCreatePostRoute
  '/account/': typeof AccountIndexRoute
  '/discussions/': typeof DiscussionsIndexRoute
  '/forum-demo/': typeof ForumDemoIndexRoute
  '/forum/': typeof ForumIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/discussions'
    | '/doubleup'
    | '/forum'
    | '/forum-demo'
    | '/items'
    | '/strategies'
    | '/units'
    | '/account/confirmation'
    | '/discussions/$slug'
    | '/forum-demo/$postId'
    | '/forum/$postId'
    | '/forum/create-post'
    | '/account/'
    | '/discussions/'
    | '/forum-demo/'
    | '/forum/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/doubleup'
    | '/items'
    | '/strategies'
    | '/units'
    | '/account/confirmation'
    | '/discussions/$slug'
    | '/forum-demo/$postId'
    | '/forum/$postId'
    | '/forum/create-post'
    | '/account'
    | '/discussions'
    | '/forum-demo'
    | '/forum'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/discussions'
    | '/doubleup'
    | '/forum'
    | '/forum-demo'
    | '/items'
    | '/strategies'
    | '/units'
    | '/account/confirmation'
    | '/discussions/$slug'
    | '/forum-demo/$postId'
    | '/forum/$postId'
    | '/forum/create-post'
    | '/account/'
    | '/discussions/'
    | '/forum-demo/'
    | '/forum/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  DiscussionsRoute: typeof DiscussionsRouteWithChildren
  DoubleupRoute: typeof DoubleupRoute
  ForumRoute: typeof ForumRouteWithChildren
  ForumDemoRoute: typeof ForumDemoRouteWithChildren
  ItemsRoute: typeof ItemsRoute
  StrategiesRoute: typeof StrategiesRoute
  UnitsRoute: typeof UnitsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/units': {
      id: '/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof UnitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies': {
      id: '/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof StrategiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum-demo': {
      id: '/forum-demo'
      path: '/forum-demo'
      fullPath: '/forum-demo'
      preLoaderRoute: typeof ForumDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doubleup': {
      id: '/doubleup'
      path: '/doubleup'
      fullPath: '/doubleup'
      preLoaderRoute: typeof DoubleupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discussions': {
      id: '/discussions'
      path: '/discussions'
      fullPath: '/discussions'
      preLoaderRoute: typeof DiscussionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/': {
      id: '/forum/'
      path: '/'
      fullPath: '/forum/'
      preLoaderRoute: typeof ForumIndexRouteImport
      parentRoute: typeof ForumRoute
    }
    '/forum-demo/': {
      id: '/forum-demo/'
      path: '/'
      fullPath: '/forum-demo/'
      preLoaderRoute: typeof ForumDemoIndexRouteImport
      parentRoute: typeof ForumDemoRoute
    }
    '/discussions/': {
      id: '/discussions/'
      path: '/'
      fullPath: '/discussions/'
      preLoaderRoute: typeof DiscussionsIndexRouteImport
      parentRoute: typeof DiscussionsRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/forum/create-post': {
      id: '/forum/create-post'
      path: '/create-post'
      fullPath: '/forum/create-post'
      preLoaderRoute: typeof ForumCreatePostRouteImport
      parentRoute: typeof ForumRoute
    }
    '/forum/$postId': {
      id: '/forum/$postId'
      path: '/$postId'
      fullPath: '/forum/$postId'
      preLoaderRoute: typeof ForumPostIdRouteImport
      parentRoute: typeof ForumRoute
    }
    '/forum-demo/$postId': {
      id: '/forum-demo/$postId'
      path: '/$postId'
      fullPath: '/forum-demo/$postId'
      preLoaderRoute: typeof ForumDemoPostIdRouteImport
      parentRoute: typeof ForumDemoRoute
    }
    '/discussions/$slug': {
      id: '/discussions/$slug'
      path: '/$slug'
      fullPath: '/discussions/$slug'
      preLoaderRoute: typeof DiscussionsSlugRouteImport
      parentRoute: typeof DiscussionsRoute
    }
    '/account/confirmation': {
      id: '/account/confirmation'
      path: '/confirmation'
      fullPath: '/account/confirmation'
      preLoaderRoute: typeof AccountConfirmationRouteImport
      parentRoute: typeof AccountRoute
    }
  }
}

interface AccountRouteChildren {
  AccountConfirmationRoute: typeof AccountConfirmationRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountConfirmationRoute: AccountConfirmationRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface DiscussionsRouteChildren {
  DiscussionsSlugRoute: typeof DiscussionsSlugRoute
  DiscussionsIndexRoute: typeof DiscussionsIndexRoute
}

const DiscussionsRouteChildren: DiscussionsRouteChildren = {
  DiscussionsSlugRoute: DiscussionsSlugRoute,
  DiscussionsIndexRoute: DiscussionsIndexRoute,
}

const DiscussionsRouteWithChildren = DiscussionsRoute._addFileChildren(
  DiscussionsRouteChildren,
)

interface ForumRouteChildren {
  ForumPostIdRoute: typeof ForumPostIdRoute
  ForumCreatePostRoute: typeof ForumCreatePostRoute
  ForumIndexRoute: typeof ForumIndexRoute
}

const ForumRouteChildren: ForumRouteChildren = {
  ForumPostIdRoute: ForumPostIdRoute,
  ForumCreatePostRoute: ForumCreatePostRoute,
  ForumIndexRoute: ForumIndexRoute,
}

const ForumRouteWithChildren = ForumRoute._addFileChildren(ForumRouteChildren)

interface ForumDemoRouteChildren {
  ForumDemoPostIdRoute: typeof ForumDemoPostIdRoute
  ForumDemoIndexRoute: typeof ForumDemoIndexRoute
}

const ForumDemoRouteChildren: ForumDemoRouteChildren = {
  ForumDemoPostIdRoute: ForumDemoPostIdRoute,
  ForumDemoIndexRoute: ForumDemoIndexRoute,
}

const ForumDemoRouteWithChildren = ForumDemoRoute._addFileChildren(
  ForumDemoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  DiscussionsRoute: DiscussionsRouteWithChildren,
  DoubleupRoute: DoubleupRoute,
  ForumRoute: ForumRouteWithChildren,
  ForumDemoRoute: ForumDemoRouteWithChildren,
  ItemsRoute: ItemsRoute,
  StrategiesRoute: StrategiesRoute,
  UnitsRoute: UnitsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
